file:
	# Make new CPP file with basic templating layout in current directory. 
	@read -p "Enter desired C++ file name WITHOUT cpp extension: " filename; \
	cp ../resources/templateFile.cpp ./src/$$filename.cpp; \
	code src/$$filename.cpp;
